version: 3.1.{build}.0
branches:
  only:
  - master
  - production
  except:
  - gh-pages
skip_non_tags: true
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.Version.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache: packages -> **\packages.config
build:
  parallel: true
  verbosity: detailed
artifacts:
- path: '**\*.nupkg'
  name: nupkg
deploy:
- provider: GitHub
  auth_token:
    secure: UKi94d2MuFkTQQi/a/fCIk77vNm1Iqi90f7PkeJKs8HVvCuGGhxlqNKKblKL6iL+
  artifact: nupkg
  draft: false
  force_update: true